Fix ignore routes
cybozu-go/kkok pull request #4
Opened 2017-09-28 05:02 UTC by uchan-nos

fix #2

2017-10-02 05:58 UTC, ymmt2005 requested changes

2017-10-02 05:58 UTC, ymmt2005 commented on kkok.go
> +			_, ok := routedAlerts[id]
`al, ok := routedAlerts[id]` としておけば、↓の append で再度取得を避けられます。
上に書いたように routedAlerts の初期化を飛ばした場合、ok チェックもしない感じで。

2017-10-02 05:58 UTC, ymmt2005 commented on kkok.go
> +	routedAlerts := make(map[string][]*Alert)
routedAlerts の計算は `k.lkr.Lock()` の前に持っていってロック期間を最小化したいですね。
そのためには、直後の for 文で `k.routes` を触っているのをやめてしまいましょうか。

routedAlerts の要素を入れなず nil を引いても、slice への append は可能なので初期化飛ばせます。

2017-10-03 04:51 UTC, uchan-nos commented on kkok.go
> +			_, ok := routedAlerts[id]
routedAlerts の初期化をなくすと，a.Routes に含まれていて k.routes には含まれていないルートのチェックがちょっと面倒になります．そのチェックは無しにしてしまって，設定ファイルに無いルートを指定すると単に無視されます，という仕様でいいでしょうか．

2017-10-03 04:57 UTC, uchan-nos commented on kkok.go
> +	routedAlerts := make(map[string][]*Alert)
routedAlerts の計算時間をロック外に出す，または削減する，というのは悪いことではないと思うのですが，しかし `t.Deliver` の実行時間がロック時間の主要な部分ですよね．
ロック時間を短くしたいなら，k.routes の一貫性はちょっとあきらめて，k.routes を別スライスへコピーして使うのがいいかなーと思いました．どうでしょう．

2017-10-03 05:59 UTC, ymmt2005 commented on kkok.go
> +			_, ok := routedAlerts[id]
はい

2017-10-03 06:02 UTC, ymmt2005 commented on kkok.go
> +	routedAlerts := make(map[string][]*Alert)
t.Deliver は時間がかかってはいけないので、時間を要する可能性がある場合
内部 queue に入れてすぐ代えるように実装しています。kkok のメインループは
シングルスレッド処理なため、時間を要する処理がそこに混じると監視間隔が
守れないのですよね。

まあ別スライスでも、初期化やめてロック外に出すのでも、どちらでもOKです。

2017-10-04 00:58 UTC, uchan-nos commented on kkok.go
> +	routedAlerts := make(map[string][]*Alert)
> t.Deliver は時間がかかってはいけない

このような仕様だったのですね．承知しました．

transports/slack の実装をぱっと見て Deliver の中で実際の送信処理をしているように見えたのですが，よく見たら channel に突っ込んでるだけでした．

2017-10-10 01:07 UTC, ymmt2005 approved these changes

2017-10-10 01:07 UTC, merged

2017-10-10 01:07 UTC, ymmt2005 commented
LGTM.  Thank you!